matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd server
      script:
        - gradle test
        - gradle jacocoTestReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: node_js
      node_js:
        - "node"
        - "7"
      before_script:
        - cd front-end
        - npm cache --force clean
        - npm install


      script:
        - npm test
notifications:
  email:
    - 3montyjack@gmail.com
