matrix:
  include:
    - language: java
      jdk: oraclejdk8
      before_script:
        - cd server
      script:
        - gradle test
    - language: node_js
      node_js:
        - "node"
        - "7"
      before_script:
        - cd front-end
        - npm install
      cache:
        directories:

      script:
        - npm test
notifications:
  webhooks:
    - webhooks: https://coveralls.io/webhook?repo_token=nCLMAOs5DadOenvkOYsIqkACo9lWnISTg
  email:
    - 3montyjack@gmail.com
