curl -X POST localhost:8080/api/printers -d '{"name": "Sully", "brand": "MakerBot", "model": "5th Gen Replicator", "status": "OPEN"}' -H "Content-Type: application/json"; echo ""
curl -X POST localhost:8080/api/printers -d '{"name": "Tiny", "brand": "MakerBot", "model": "Z-18", "status": "OPEN"}' -H "Content-Type: application/json"; echo ""
curl -X POST localhost:8080/api/printers -d '{"name": "Stitch", "brand": "MakerBot", "model": "5th Gen Replicator", "status": "OPEN"}' -H "Content-Type: application/json"; echo ""
curl -X POST localhost:8080/api/printers -d '{"name": "Adam", "brand": "MakerBot", "model": "5th Gen Replicator", "status": "OPEN"}' -H "Content-Type: application/json"; echo ""
curl -X POST localhost:8080/api/printers -d '{"name": "Phillip", "brand": "MakerBot", "model": "5th Gen Replicator", "status": "OPEN"}' -H "Content-Type: application/json"; echo ""
curl -X POST localhost:8080/api/printers -d '{"name": "Lilo", "brand": "MakerBot", "model": "5th Gen Replicator", "status": "OPEN"}' -H "Content-Type: application/json"; echo ""
curl -X POST localhost:8080/api/printers -d '{"name": "Geoffrey", "brand": "MakerBot", "model": "5th Gen Replicator", "status": "OPEN"}' -H "Content-Type: application/json"; echo ""
curl -X POST localhost:8080/api/printers -d '{"name": "Bruce", "brand": "MakerBot", "model": "5th Gen Replicator", "status": "OPEN"}' -H "Content-Type: application/json"; echo ""

curl -X POST localhost:8080/api/requests -d '{"user": "kyteg", "forClass": true, "requestItems": [{"fileName": "AppleBottom.stl", "color": "red", "qty": 1},{"fileName": "BootsWFur.stl", "color": "black", "qty": 2},{"fileName": "Club.stl", "color": "any", "qty": 1}] }' -H "Content-Type: application/json"; echo ""
curl -X POST localhost:8080/api/requests -d '{"user": "3montyjack", "comments": "Pistaccios can lower risk of heart disease", "forClass": true, "requestItems": [{"fileName": "https://www.thingiverse.com/thing:222667", "color": "blue", "qty": 2}] }' -H "Content-Type: application/json"; echo ""
curl -X POST localhost:8080/api/requests -d '{"user": "jihang", "comments": "Is this how I print in color?", "forClass": false, "requestItems": [{"fileName": "Essay.pdf", "color": "all", "qty": 1}] }' -H "Content-Type: application/json"; echo ""
curl -X POST localhost:8080/api/requests -d '{"user": "sinkhornb", "comments": "This should fix the extruder that broke", "forClass": false, "requestItems": [{"fileName": "https://www.thingiverse.com/thing:222667", "color": "black", "qty": 1}] }' -H "Content-Type: application/json"; echo ""
curl -X POST localhost:8080/api/requests -d '{"user": "ghberemeskels", "comments": "The longest side is 3inches. You can print all on one plate.", "forClass": true, "requestItems": [{"fileName": "puzzlePiece-A", "color": "red", "qty": 5}, {"fileName": "puzzlePiece-B", "color": "orange", "qty": 5}, {"fileName": "puzzlePiece-C", "color": "yellow", "qty": 5}]}' -H "Content-Type: application/json"; echo ""

curl -X POST localhost:8080/api/users -d '{"firstName": "Gavin", "lastName": "Kyte", "email": "kyteg@xavier.edu", "username": "kyteg"}' -H "Content-Type: application/json"; echo ""
curl -X POST localhost:8080/api/users -d '{"firstName": "Solomon", "lastName": "Ghberemeskle", "email": "ghberemeskles@xavier.edu", "username": "ghberemeskle"}' -H "Content-Type: application/json"; echo ""
